version: '2'
services:
  docker-devops:
    extends:
      file: common.yml
      service: docker-devops
    image: ecarlste/docker-devops
    environment:
      - constraint:node==master
    depends_on:
      - redis
    networks:
      - mynet

  redis:
    extends:
      file: common.yml
      service: redis
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
